branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - '12'
cache: yarn
deploy:
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
